const images_antibatterici = [
    'antibatterici/fenossimetilpenicillina.png',
    'antibatterici/benzilpenicillina.png',
    'antibatterici/meticillina.png',
    'antibatterici/nafcillina.png',
    'antibatterici/oxacillina.png',
    'antibatterici/cloxacillina.png',
    'antibatterici/dicloxacillina.png',
    'antibatterici/flucloxacillina.png',
    'antibatterici/ampicillina.png',
    'antibatterici/amoxicillina.png',
    'antibatterici/pivampicillina.png',
    'antibatterici/mezlocillina.png',
    'antibatterici/piperacillina.png',
    'antibatterici/azlocillina.png',
    'antibatterici/carbenicillina.png',
    'antibatterici/ticarcillina.png',
    'antibatterici/sulbenicillina.png',
    'antibatterici/probenecid.png',
    'antibatterici/acidoclavulanico.png',
    'antibatterici/sulbactam.png',
    'antibatterici/tazobactam.png',
    'antibatterici/cefalexina.png',
    'antibatterici/cefalotina.png',
    'antibatterici/cefaloridina.png',
    'antibatterici/cefadroxile.png',
    'antibatterici/cefuroxima_axetil.png',
    'antibatterici/cefoxitina.png',
    'antibatterici/cefuroxima.png',
    'antibatterici/cefaclor.png',
    'antibatterici/cefotaxima.png',
    'antibatterici/ceftizoxima.png',
    'antibatterici/ceftriaxone.png',
    'antibatterici/ceftazidima.png',
    'antibatterici/cefepima.png',
    'antibatterici/tienamicina.png',
    'antibatterici/imipenem.png',
    'antibatterici/ertapenem.png',
    'antibatterici/meropenem.png',
    'antibatterici/aztreonam.png',
    'antibatterici/cicloserina.png',
    'antibatterici/fosfomicina.png',
    'antibatterici/eritromicina.png',
    'antibatterici/claritromicina.png',
    'antibatterici/azitromicina.png',
    'antibatterici/tetraciclina.png',
    'antibatterici/demeclociclina.png',
    'antibatterici/clortetraciclina.png',
    'antibatterici/minociclina.png',
    'antibatterici/doxiciclina.png',
    'antibatterici/metaciclina.png',
    'antibatterici/ossitetraciclina.png',
    'antibatterici/tigeciclina.png',
    'antibatterici/streptomicina.png',
    'antibatterici/kanamicina.png',
    'antibatterici/gentamicina.png',
    'antibatterici/neomicina.png',
    'antibatterici/amicacina.png',
    'antibatterici/netilmicina.png',
    'antibatterici/tobramicina.png',
    'antibatterici/rifampicina.png',
    'antibatterici/cloramfenicolo.png',
    'antibatterici/tiamfenicolo.png',
    'antibatterici/sulfafurazolo.png',
    'antibatterici/sulfatiazolo.png',
    'antibatterici/sulfadimetossina.png',
    'antibatterici/sulfametossipiridina.png',
    'antibatterici/sulfaguanidina.png',
    'antibatterici/sulfacetamide.png',
    'antibatterici/sulfadiazina.png',
    'antibatterici/sulfalene.png',
    'antibatterici/sulfadossina.png',
    'antibatterici/sulfametossazolo.png',
    'antibatterici/sulfisossazolo.png',
    'antibatterici/acido_nalidixico.png',
    'antibatterici/cinoxacina.png',
    'antibatterici/acido_oxolinico.png',
    'antibatterici/acido_pipemidico.png',
    'antibatterici/norfloxacina.png',
    'antibatterici/ofloxacina.png',
    'antibatterici/grepafloxacina.png',
    'antibatterici/sparfloxacina.png',
    'antibatterici/gemifloxacina.png',
    'antibatterici/moxifloxacina.png',
    'antibatterici/trimetoprim.png',
];

const images_chinoloni = [
    'chinoloni/acido_nalidixico.jpg',
    'chinoloni/cinoxacina.jpg',
    'chinoloni/acido_oxolinico.jpg',
    'chinoloni/acido_pipemidico.jpg',
    'chinoloni/norfloxacina.jpg',
    'chinoloni/ofloxacina.jpg',
    'chinoloni/grepafloxacina.jpg',
    'chinoloni/sparfloxacina.jpg',
    'chinoloni/gemifloxacina.jpg',
    'chinoloni/moxifloxacina.jpg',
    'chinoloni/ciprofloxacina.jpg',
    'chinoloni/levofloxacina.jpg',
    'chinoloni/clinafloxacina.jpg'
];

const images_sulfamidici = [
    'sulfamidici/sulfafurazolo.png',
    'sulfamidici/sulfatiazolo.png',
    'sulfamidici/sulfadimetossina.png',
    'sulfamidici/sulfametossipiridazina.png',
    'sulfamidici/sulfaguanidina.png',
    'sulfamidici/sulfacetamide.png',
    'sulfamidici/sulfadiazina.png',
    'sulfamidici/sulfalene.png',
    'sulfamidici/sulfadossina.png',
    'sulfamidici/sulfametossazolo.png',
    'sulfamidici/sulfisossazolo.png',
    'sulfamidici/sulfasalazina.png',
    'sulfamidici/succinilsulfatiazolo.png',
    'sulfamidici/ftalilsulfatiazolo.png',
];

const images_antifungini = [
    'antifungini/nistatina.png',
    'antifungini/amfotericinab.png',
    'antifungini/miconazolo.png',
    'antifungini/econazolo.png',
    'antifungini/sulconazolo.png',
    'antifungini/tioconazolo.png',
    'antifungini/ketoconazolo.png',
    'antifungini/fluconazolo.png',
    'antifungini/voriconazolo.png',
    'antifungini/clotrimazolo.png',
    'antifungini/itroconazolo.png',
    'antifungini/posaconazolo.png',
    'antifungini/caspofungin.png',
    'antifungini/micafungin.png',
    'antifungini/anidulafungin.png',
    'antifungini/flucitosina.png',
    'antifungini/griseofulvina.png',
];

const images_antimalarici = [
    'antimalarici/chinina.png',
    'antimalarici/clorochina.png',
    'antimalarici/mepacrina.png',
    'antimalarici/primachina.png',
    'antimalarici/rubano.png',
    'antimalarici/meflochina.png',
    'antimalarici/amodiachina.png',
    'antimalarici/idrossiclorochina.png',
    'antimalarici/alofantrina.png',
    'antimalarici/trimetoprim.png',
    'antimalarici/primetamina.png',
    'antimalarici/proguanile.png',
    'antimalarici/artemisina.png',
    'antimalarici/atovaquone.png',
];

const images_antitumorali = [
    'antitumorali/clorambucile.png',
    'antitumorali/melfalan.png',
    'antitumorali/ciclofosfamide.png',
    'antitumorali/ifosfamide.png',
    'antitumorali/busulfan.png',
    'antitumorali/dacarbazina.png',
    'antitumorali/temozolomide.png',
    'antitumorali/tiotepa.png',
    'antitumorali/mitomicina_c.png',
    'antitumorali/carmustina.png',
    'antitumorali/lomustina.png',
    'antitumorali/streptozocina.png',
    'antitumorali/cisplatino.png',
    'antitumorali/carboplatino.png',
    'antitumorali/oxaliplatino.png',
    'antitumorali/doxorubicina.png',
    'antitumorali/daunorubicina.png',
    'antitumorali/idarubicina.png',
    'antitumorali/epirubicina.png',
    'antitumorali/mitoxantrone.png',
    'antitumorali/dactinomicina.png',
    'antitumorali/camptotecina.png',
    'antitumorali/topotecan.png',
    'antitumorali/irinotecan.png',
    'antitumorali/bleomicina.png',
    'antitumorali/5_fluoro_uracile.png',
    'antitumorali/folfox.png',
    'antitumorali/capecitabina.png',
    'antitumorali/citarabina.png',
    'antitumorali/gemcitabina.png',
    'antitumorali/pemetrexed.png',
    'antitumorali/fludarabina.png',
    'antitumorali/6_mercaptopurina.png',
    'antitumorali/6_tioguanina.png',
    'antitumorali/aminopterina.png',
    'antitumorali/metotrexato.png',
    'antitumorali/raltitrexed.png',
    'antitumorali/vincristina.png',
    'antitumorali/vinblastina.png',
    'antitumorali/paclitaxel.png',
    'antitumorali/docetaxel.png',
    'antitumorali/imatinib.png',
    'antitumorali/ponatinib.png',
    'antitumorali/gefitinib.png',
    'antitumorali/erlotinib.png',
    'antitumorali/lapatinib.png',
];

const images_antivirali = [
    'antivirali/aciclovir.png',
    'antivirali/ganciclovir.png',
    'antivirali/penciclovir.png',
    'antivirali/valaciclovir.png',
    'antivirali/famciclovir.png',
    'antivirali/cidofovir.png',
    'antivirali/adefovir.png',
    'antivirali/tenofovir.png',
    'antivirali/idoxuridina.png',
    'antivirali/foscarnet.png',
    'antivirali/trifluridina.png',
    'antivirali/brivudina.png',
    'antivirali/zidovudina.png',
    'antivirali/didanosina.png',
    'antivirali/zalcitabina.png',
    'antivirali/stavudina.png',
    'antivirali/lamivudina.png',
    'antivirali/remdesevir.png',
    'antivirali/tenofovir_alafenamide.png',
    'antivirali/sofosbuvir.png',
    'antivirali/nevirapina.png',
    'antivirali/delavirdina.png',
    'antivirali/DPC083.png',
    'antivirali/efavirenz.png',
    'antivirali/emivirina.png',
    'antivirali/rilpivirina.png',
    'antivirali/saquinavir.png',
    'antivirali/indinavir.png',
    'antivirali/ritonavir.png',
    'antivirali/nelfinavir.png',
    'antivirali/lopinavir.png',
    'antivirali/raltegravir.png',
    'antivirali/enfuvirtide.png',
    'antivirali/maraviroc.png',
    'antivirali/amantadina.png',
    'antivirali/rimantadina.png',
    'antivirali/zanamavir.png',
    'antivirali/oseltamavir.png',
    'antivirali/ribavirina.png',
    'antivirali/molnupiravir.png',
    'antivirali/favipiravir.png',
    'antivirali/nirmatrelvir.png',
    'antivirali/MEDS433.png',
];

// Mappa degli array di immagini
const imagesMap = {
    'antibatterici': images_antibatterici,
    'chinoloni': images_chinoloni,
    'sulfamidici': images_sulfamidici,
    'antifungini': images_antifungini,
    'antimalarici': images_antimalarici,
    'antitumorali': images_antitumorali,
    'antivirali': images_antivirali
};

function showRandomImage(param) {
    // Seleziona l'array corretto in base al parametro
    const images = imagesMap[param];
    console.log(images, param)
    // Verifica se l'array di immagini esiste e non è vuoto
    if (images && images.length > 0) {
        const randomIndex = Math.floor(Math.random() * images.length);
        const randomImage = images[randomIndex];
        const imgElement = document.getElementById("drugImage");
        imgElement.src = randomImage;
        imgElement.style.display = "block";
    } else {
        console.error("Nessuna immagine trovata per il parametro:", param);
    }
}